apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  labels:
    app: nats
    app.kubernetes.io/name: nats
    app.kubernetes.io/component: messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:2.10-alpine
          ports:
            - containerPort: 4222
              name: client
            - containerPort: 8222
              name: monitor
            - containerPort: 6222
              name: cluster
          args:
            - "--http_port=8222"
            - "--port=4222"
            - "--cluster_name=cinema-nats"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8222
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8222
            initialDelaySeconds: 5
            periodSeconds: 5
