apiVersion: v1
kind: Service
metadata:
  name: nats
  labels:
    app: nats
    app.kubernetes.io/name: nats
    app.kubernetes.io/component: messaging
spec:
  type: ClusterIP
  ports:
    - port: 4222
      targetPort: 4222
      protocol: TCP
      name: client
    - port: 8222
      targetPort: 8222
      protocol: TCP
      name: monitor
  selector:
    app: nats
