apiVersion: v1
kind: Service
metadata:
  name: seat-service
  labels:
    app.kubernetes.io/name: seat-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8005
      targetPort: http
  selector:
    app.kubernetes.io/name: seat-service
