quarkus.application.name=loyalty
quarkus.http.port=8011

# Health
quarkus.smallrye-health.root-path=/q/health

# Logging
quarkus.log.level=INFO
quarkus.log.category."dev.cinema.latam".level=DEBUG

# Metrics
quarkus.micrometer.export.prometheus.path=/q/metrics
