trigger:
  name: Merge PR
  identifier: Merge_PR
  enabled: true
  stagesToExecute:
    - push_image
  description: ""
  tags: {}
  encryptedWebhookSecretIdentifier: ""
  orgIdentifier: sandbox
  projectIdentifier: CristianRamirez
  pipelineIdentifier: ci_shift_left_security
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: PullRequest
        spec:
          connectorRef: CristianConnector
          autoAbortPreviousExecutions: true
          payloadConditions:
            - key: changedFiles
              operator: Regex
              value: ^services/py-app-demo/.*
            - key: targetBranch
              operator: Equals
              value: monorepo
          headerConditions: []
          repoName: cinema-microservice-in-GO
          actions:
            - Close
  inputYaml: |
    pipeline:
      identifier: ci_shift_left_security
      properties:
        ci:
          codebase:
            build:
              type: PR
              spec:
                number: <+trigger.prNumber>
