kind: System
spec:
  owner: cristian.ramirez@harness.io
  domain: default
apiVersion: backstage.io/v1alpha1
metadata:
  name: cristian_labs_manual_setup
  links:
    - url: https://app.harness.io/ng/account/6_vVHzo9Qeu9fXvj-AcbCQ/home/orgs/default/projects/Platform_Demo/details
      title:  Harness Platform Demo Project
      icon: dashboard
      type: Harness Platform Demo Project
    - url: https://app.harness.io/ng/account/6_vVHzo9Qeu9fXvj-AcbCQ/cd/orgs/default/projects/Platform_Demo/pipelines/EndtoEnd_Pipeline_SVC_Redesign/pipeline-studio/?storeType=INLINE
      title: Harness Plaforrm Story
      icon: dashboard
      type: Harness Plaforrm Story
    - url: http://34.67.7.165/
      title: Prod Website
      icon: dashboard
      type: Boutique FrontEnd
    - url: http://34.28.46.65
      title: QA Website
      icon: dashboard
      type: Boutique FrontEnd
    - url: http://34.135.60.81/
      title: Dev Website
      icon: dashboard
      type: Boutique FrontEnd
  description: "Documentation: https://harness.atlassian.net/wiki/spaces/SE/pages/1783103570/Platform+Demo+Block"
  tags: []
