apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app.kubernetes.io/name: user-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8004
      targetPort: http
  selector:
    app.kubernetes.io/name: user-service
