apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-nats
  namespace: argocd
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: cinema-microservices
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/crizstian/cinema-microservice-in-GO.git
    targetRevision: monorepo
    path: platform/deploy/gitops/infrastructure/nats/base
  destination:
    server: https://kubernetes.default.svc
    namespace: cinema-infra
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
