apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app.kubernetes.io/name: payment-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8007
      targetPort: http
  selector:
    app.kubernetes.io/name: payment-service
