version: "3.8"

services:
  infra-dev:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    env_file:
      - .env
    volumes:
      - ../:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.config/gcloud:/home/devuser/.config/gcloud:ro
      - ${HOME}/.kube:/home/devuser/.kube:ro
      - ${HOME}/.aws:/home/devuser/.aws:ro
    working_dir: /workspace
    user: devuser
    container_name: infra-dev
    command: /bin/bash -c "while sleep 1000; do :; done"
