version: "3.8"

services:
  cinemas_microservice_go:
    build:
      context: ../platform/docker/devcontainer
      dockerfile: Dockerfile
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    env_file:
      - .env
    volumes:
      - ../:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.config/gcloud:/home/devuser/.config/gcloud:rw
      - ${HOME}/.kube:/home/devuser/.kube:rw
    working_dir: /workspace
    user: devuser
    container_name: cinemas_microservice_go
    command: /bin/sh -c "while sleep 1000; do :; done"
