# Cinema Service Values
# Manages cinema locations and halls

serviceName: cinema-service
version: <+artifact.tag>

port: 8003
dbName: cinema

dependencies: []

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  minReplicas: 1
  maxReplicas: 5

pdb:
  minAvailable: 1
