# Showtime Service Values
# Manages movie showtimes

serviceName: showtime-service
version: <+artifact.tag>

port: 8006
dbName: showtime

dependencies:
  - movie-service
  - cinema-service

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  minReplicas: 1
  maxReplicas: 5

pdb:
  minAvailable: 1
