# Harness Service Definition
# GitOps pattern - configuration lives in values files, not here

service:
  name: movie-service
  identifier: movieservice
  serviceDefinition:
    type: Kubernetes
    spec:
      manifests:
        - manifest:
            identifier: templates
            type: K8sManifest
            spec:
              store:
                type: Github
                spec:
                  connectorRef: CristianConnector
                  gitFetchType: Branch
                  paths:
                    - platform/deploy/kubernetes/templates/services/
                  repoName: cinema-microservice-in-GO
                  branch: <+pipeline.variables.branch>
              valuesPaths:
                - platform/deploy/kubernetes/values/base.yaml
                - platform/deploy/kubernetes/values/environments/<+env.name>.yaml
                - platform/deploy/kubernetes/values/services/movie.yaml
              skipResourceVersioning: true
      artifacts:
        primary:
          primaryArtifactRef: artifact
          sources:
            - identifier: artifact
              type: DockerRegistry
              spec:
                connectorRef: DockerCristian
                imagePath: crizstian/movie-service
                tag: <+input>
  gitOpsEnabled: false
