apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cinema-prod

resources:
  - ../../base

commonLabels:
  app.kubernetes.io/environment: prod
  harness.io/envRef: prod

images:
  - name: crizstian/showtime-service
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: showtime-service
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: ConfigMap
      name: showtime-service-config
    patch: |
      - op: add
        path: /data/LOG_LEVEL
        value: warn
      - op: add
        path: /data/DB_SERVERS
        value: mongodb.cinema-infra.svc.cluster.local:27017
      - op: add
        path: /data/NATS_URL
      - op: add
        path: /data/PAYMENT_URL
        value: http://payment-service.cinema-prod.svc.cluster.local:8007
      - op: add
        path: /data/NOTIFICATION_URL
        value: http://notification-service.cinema-prod.svc.cluster.local:8008
      - op: add
        path: /data/SEAT_SERVICE_URL
        value: http://seat-service.cinema-prod.svc.cluster.local:8005
      - op: add
        path: /data/SHOWTIME_SERVICE_URL
        value: http://showtime-service.cinema-prod.svc.cluster.local:8006
      - op: add
        path: /data/MOVIE_SERVICE_URL
        value: http://movie-service.cinema-prod.svc.cluster.local:8002
      - op: add
        path: /data/CINEMA_SERVICE_URL
        value: http://cinema-service.cinema-prod.svc.cluster.local:8003
      - op: add
        path: /data/USER_SERVICE_URL
        value: http://user-service.cinema-prod.svc.cluster.local:8004
      - op: add
        path: /data/BOOKING_SERVICE_URL
        value: http://booking-service.cinema-prod.svc.cluster.local:8001
        value: nats://nats.cinema-infra.svc.cluster.local:4222
  - target:
      kind: HorizontalPodAutoscaler
      name: showtime-service
    patch: |
      - op: replace
        path: /spec/minReplicas
        value: 3
      - op: replace
        path: /spec/maxReplicas
        value: 10
