apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cinema-staging

resources:
  - ../../base

commonLabels:
  app.kubernetes.io/environment: staging
  harness.io/envRef: staging

images:
  - name: crizstian/seat-service
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: seat-service
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: ConfigMap
      name: seat-service-config
    patch: |
      - op: add
        path: /data/LOG_LEVEL
        value: info
      - op: add
        path: /data/DB_SERVERS
        value: mongodb.cinema-infra.svc.cluster.local:27017
      - op: add
        path: /data/MONGO_URI
        value: mongodb://mongodb.cinema-infra.svc.cluster.local:27017
      - op: add
        path: /data/MONGO_DB
        value: cinema_seats
      - op: add
        path: /data/NATS_URL
        value: nats://nats.cinema-infra.svc.cluster.local:4222
      - op: add
        path: /data/PAYMENT_URL
        value: http://payment-service.cinema-staging.svc.cluster.local:8007
      - op: add
        path: /data/NOTIFICATION_URL
        value: http://notification-service.cinema-staging.svc.cluster.local:8008
      - op: add
        path: /data/SEAT_SERVICE_URL
        value: http://seat-service.cinema-staging.svc.cluster.local:8005
      - op: add
        path: /data/SHOWTIME_SERVICE_URL
        value: http://showtime-service.cinema-staging.svc.cluster.local:8006
      - op: add
        path: /data/MOVIE_SERVICE_URL
        value: http://movie-service.cinema-staging.svc.cluster.local:8002
      - op: add
        path: /data/CINEMA_SERVICE_URL
        value: http://cinema-service.cinema-staging.svc.cluster.local:8003
      - op: add
        path: /data/USER_SERVICE_URL
        value: http://user-service.cinema-staging.svc.cluster.local:8004
      - op: add
        path: /data/BOOKING_SERVICE_URL
        value: http://booking-service.cinema-staging.svc.cluster.local:8001
      - op: add
        path: /data/REDIS_ADDR
        value: redis.cinema-infra.svc.cluster.local:6379
  - target:
      kind: HorizontalPodAutoscaler
      name: seat-service
    patch: |
      - op: replace
        path: /spec/minReplicas
        value: 2
      - op: replace
        path: /spec/maxReplicas
        value: 5
