apiVersion: v1
kind: Service
metadata:
  name: movie-service
  labels:
    app.kubernetes.io/name: movie-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8002
      targetPort: http
  selector:
    app.kubernetes.io/name: movie-service
