apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  labels:
    app.kubernetes.io/name: notification-service
data:
  SERVICE_NAME: notification-service
  SERVICE_PORT: "8008"
  DB_NAME: notification
  LOG_LEVEL: info
