apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app.kubernetes.io/name: notification-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8008
      targetPort: http
  selector:
    app.kubernetes.io/name: notification-service
