apiVersion: v1
kind: Service
metadata:
  name: showtime-service
  labels:
    app.kubernetes.io/name: showtime-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8006
      targetPort: http
  selector:
    app.kubernetes.io/name: showtime-service
