Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "shell", path: "provision/scripts/install.sh", args: "true true", privileged: false
  
  ['dc1'].each do |dc|
  
    ip_prefix = dc == 'dc1' ? '172.20.20.11' : '172.20.20.31'

    config.vm.define "#{dc}-consul-server" do |cs|
      cs.vm.hostname = "#{dc}-consul-server"
      cs.vm.network "private_network", ip: "#{ip_prefix}"
      cs.vm.provision "shell", path: "provision/scripts/init.hashi.sh", args: "#{dc} #{ip_prefix}", privileged: false
      cs.vm.provision "shell", path: "provision/scripts/install.dnsmasq.sh", privileged: false

      if dc == "dc1"
        # MongoDB Ports
        cs.vm.network :forwarded_port, guest: 27017, guest_ip:"10.0.2.15", host: 27017, host_ip:"0.0.0.0"
        cs.vm.network :forwarded_port, guest: 27018, guest_ip:"10.0.2.15", host: 27018, host_ip:"0.0.0.0"
        cs.vm.network :forwarded_port, guest: 27019, guest_ip:"10.0.2.15", host: 27019, host_ip:"0.0.0.0"
        # Mesh GW
        cs.vm.network :forwarded_port, guest: 8433,  guest_ip:"10.0.2.15", host: 8433,  host_ip:"0.0.0.0"
        # jaeger
        cs.vm.network :forwarded_port, guest: 16686,  guest_ip:"10.0.2.15", host: 16686,  host_ip:"0.0.0.0"
        # grafana
        cs.vm.network :forwarded_port, guest: 3999,  guest_ip:"10.0.2.15", host: 3999,  host_ip:"0.0.0.0"
      end
      if dc == "dc2"
        # Mesh GW
        cs.vm.network :forwarded_port, guest: 9433,  guest_ip:"10.0.2.15", host: 9433,  host_ip:"0.0.0.0"
      end
      
      cs.vm.provision "shell", privileged: false, inline: <<-EOF
        echo "Vagrant Box provisioned!"
      EOF
      
    end

  end
end