apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.serviceName }}
    app.kubernetes.io/version: {{ quote .Values.version }}
    app.kubernetes.io/component: pdb
    app.kubernetes.io/environment: {{ .Values.environment }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.serviceName }}
