apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.serviceName }}
    app.kubernetes.io/version: {{ quote .Values.version }}
    app.kubernetes.io/component: service
    app.kubernetes.io/environment: {{ .Values.environment }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.serviceName }}
