version: '3'

services:
  consul-dc1:
    image: consul:1.6.0
    command: ["consul","agent","-config-dir=/config"]
    volumes:
      - "./consul_config/dc1:/config"
    ports:
      - 8500:8500
    networks:
      dc1:
        ipv4_address: 10.7.0.2
      # wan:
      #   ipv4_address: 192.169.7.2

  mongo1:
    image: crizstian/cinemas-db:v0.1
    ports:
      - "27017:27017"
    environment:
      DB_ADMIN_USER: "cristian"
      DB_ADMIN_PASS: "cristianPassword2017"
      DB_REPLICA_ADMIN: "replicaAdmin"
      DB_REPLICA_ADMIN_PASS: "replicaAdminPassword2017"
      DB_REPLSET_NAME: "rs1"
      DB_PORT: "27017"
      DB1: "10.7.0.3"
      DB2: "10.7.0.4"
      DB3: "10.7.0.5"
      IS_PRIMARY: "false"
    networks:
      dc1:
        ipv4_address: 10.7.0.3

  mongo2:
    image: crizstian/cinemas-db:v0.1
    ports:
      - "27018:27017"
    environment:
      DB_ADMIN_USER: "cristian"
      DB_ADMIN_PASS: "cristianPassword2017"
      DB_REPLICA_ADMIN: "replicaAdmin"
      DB_REPLICA_ADMIN_PASS: "replicaAdminPassword2017"
      DB_REPLSET_NAME: "rs1"
      DB_PORT: "27017"
      DB1: "10.7.0.3"
      DB2: "10.7.0.4"
      DB3: "10.7.0.5"
      IS_PRIMARY: "false"
    networks:
      dc1:
        ipv4_address: 10.7.0.4

  mongo3:
    image: crizstian/cinemas-db:v0.1
    ports:
      - "27019:27017"
    environment:
      DB_ADMIN_USER: "cristian"
      DB_ADMIN_PASS: "cristianPassword2017"
      DB_REPLICA_ADMIN: "replicaAdmin"
      DB_REPLICA_ADMIN_PASS: "replicaAdminPassword2017"
      DB_REPLSET_NAME: "rs1"
      DB_PORT: "27017"
      DB3: "10.7.0.3"
      DB2: "10.7.0.4"
      DB1: "10.7.0.5"
      IS_PRIMARY: "true"
    depends_on:
      - mongo1
      - mongo2
    networks:
      dc1:
        ipv4_address: 10.7.0.5

  movie_dc1:
    image: crizstian/movies-service-go:v0.1
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      DB_USER: "cristian"
      DB_PASS: "cristianPassword2017"
      DB_SERVERS: "10.7.0.3:27017,10.7.0.4:27017,10.7.0.5:27017"
      DB_NAME: "movies"
      DB_REPLICA: "rs1"
      SERVICE_PORT: "8000"
    depends_on:
      - mongo3
    networks:
      dc1:
        ipv4_address: 10.7.0.6
  movie_envoy_dc1:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.7.0.2:8500
      CONSUL_GRPC_ADDR: 10.7.0.2:8502
      SERVICE_CONFIG: /config/movie-dc1.hcl
    volumes:
      - "./consul_config/service_config:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "movie-dc1"]
    network_mode: "service:movie_dc1"

  payment_dc1:
    image: crizstian/payment-service-go:v0.1
    restart: on-failure
    ports:
      - "8100:8000"
    environment:
      DB_USER: "cristian"
      DB_PASS: "cristianPassword2017"
      DB_SERVERS: "10.7.0.3:27017,10.7.0.4:27017,10.7.0.5:27017"
      DB_NAME: "payment"
      DB_REPLICA: "rs1"
      SERVICE_PORT: "8000"
      STRIPE_SECRET: "${STRIPE_SECRET}"
      STRIPE_PUBLIC: "${STRIPE_PUBLIC}"
    depends_on:
      - mongo3
    networks:
      dc1:
        ipv4_address: 10.7.0.7
  payment_envoy_dc1:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.7.0.2:8500
      CONSUL_GRPC_ADDR: 10.7.0.2:8502
      SERVICE_CONFIG: /config/payment-dc1.hcl
    volumes:
      - "./consul_config/service_config:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "payment-dc1"]
    network_mode: "service:payment_dc1"

  notification_dc1:
    image: crizstian/notification-service-go:v0.1
    restart: on-failure
    ports:
      - "8200:8000"
    environment:
      SERVICE_PORT: "8000"
      EMAIL: "${EMAIL}"
      EMAIL_PASS: "${EMAIL_PASS}"
    networks:
      dc1:
        ipv4_address: 10.7.0.8
  notification_envoy_dc1:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.7.0.2:8500
      CONSUL_GRPC_ADDR: 10.7.0.2:8502
      SERVICE_CONFIG: /config/notification-dc1.hcl
    volumes:
      - "./consul_config/service_config:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "notification-dc1"]
    network_mode: "service:notification_dc1"


  booking:
    image: crizstian/booking-service-go:v0.1
    restart: on-failure
    ports:
      - "8300:8000"
    environment:
      DB_USER: "cristian"
      DB_PASS: "cristianPassword2017"
      DB_SERVERS: "10.7.0.3:27017,10.7.0.4:27017,10.7.0.5:27017"
      DB_NAME: "booking"
      DB_REPLICA: "rs1"
      SERVICE_PORT: "8000"
      PAYMENT_URL: "http://10.7.0.7:8000"
      NOTIFICATION_URL: "http://10.7.0.8:8000"
    networks:
      dc1:
        ipv4_address: 10.7.0.9
  booking_envoy:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.7.0.2:8500
      CONSUL_GRPC_ADDR: 10.7.0.2:8502
      SERVICE_CONFIG: /config/booking-service.hcl
      CENTRAL_CONFIG_DIR: "/central_config"
    volumes:
      - "./consul_config/service_config:/config"
      - "./consul_config/central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "booking"]
    network_mode: "service:booking"

networks:
  dc1:
    driver: bridge
    ipam:
     config:
       - subnet: 10.7.0.0/16