version: "3.3"
services:

  mongo1:
    image: crizstian/cinemas-db:v0.1
    environment:
      DB_ADMIN_USER: "cristian"
      DB_ADMIN_PASS: "cristianPassword2017"
      DB_REPLICA_ADMIN: "replicaAdmin"
      DB_REPLICA_ADMIN_PASS: "replicaAdminPassword2017"
      DB_REPLSET_NAME: "rs1"
      DB_PORT: "27017"
      DB1: "10.10.0.3"
      DB2: "10.10.0.4"
      DB3: "10.10.0.5"
      IS_PRIMARY: "false"
    networks:
      dc1:
        ipv4_address: 10.10.0.3

  mongo2:
    image: crizstian/cinemas-db:v0.1
    environment:
      DB_ADMIN_USER: "cristian"
      DB_ADMIN_PASS: "cristianPassword2017"
      DB_REPLICA_ADMIN: "replicaAdmin"
      DB_REPLICA_ADMIN_PASS: "replicaAdminPassword2017"
      DB_REPLSET_NAME: "rs1"
      DB_PORT: "27017"
      DB1: "10.10.0.3"
      DB2: "10.10.0.4"
      DB3: "10.10.0.5"
      IS_PRIMARY: "false"
    networks:
      dc1:
        ipv4_address: 10.10.0.4

  mongo3:
    image: crizstian/cinemas-db:v0.1
    environment:
      DB_ADMIN_USER: "cristian"
      DB_ADMIN_PASS: "cristianPassword2017"
      DB_REPLICA_ADMIN: "replicaAdmin"
      DB_REPLICA_ADMIN_PASS: "replicaAdminPassword2017"
      DB_REPLSET_NAME: "rs1"
      DB_PORT: "27017"
      DB3: "10.10.0.3"
      DB2: "10.10.0.4"
      DB1: "10.10.0.5"
      IS_PRIMARY: "true"
    depends_on:
      - mongo1
      - mongo2
    networks:
      dc1:
        ipv4_address: 10.10.0.5

  payment_dc1:
    image: crizstian/payment-service-go:v0.1
    restart: on-failure
    environment:
      DB_USER: "cristian"
      DB_PASS: "cristianPassword2017"
      DB_SERVERS: "10.10.0.3:27017,10.10.0.4:27017,10.10.0.5:27017"
      DB_NAME: "payment"
      DB_REPLICA: "rs1"
      SERVICE_PORT: "8000"
      STRIPE_SECRET: "${STRIPE_SECRET}"
      STRIPE_PUBLIC: "${STRIPE_PUBLIC}"
    depends_on:
      - mongo3
    networks:
      dc1:
        ipv4_address: 10.10.0.7

  notification_dc1:
    image: crizstian/notification-service-go:v0.1
    restart: on-failure
    environment:
      SERVICE_PORT: "8000"
      EMAIL: "${EMAIL}"
      EMAIL_PASS: "${EMAIL_PASS}"
    networks:
      dc1:
        ipv4_address: 10.10.0.8

  booking:
    image: crizstian/booking-service-go:v0.1
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      DB_USER: "cristian"
      DB_PASS: "cristianPassword2017"
      DB_SERVERS: "10.10.0.3:27017,10.10.0.4:27017,10.10.0.5:27017"
      DB_NAME: "booking"
      DB_REPLICA: "rs1"
      SERVICE_PORT: "8000"
      PAYMENT_URL: "http://10.10.0.7:9091"
      NOTIFICATION_URL: "http://10.10.0.8:9092"
    networks:
      dc1:
        ipv4_address: 10.10.0.9
    depends_on:
      - mongo3

networks:
  dc1:
    driver: bridge
    ipam:
     config:
       - subnet: 10.10.0.0/16