apiVersion: v1
kind: Service
metadata:
  name: cinema-service
  labels:
    app.kubernetes.io/name: cinema-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8003
      targetPort: http
  selector:
    app.kubernetes.io/name: cinema-service
